### ISSUE TITLE
Unable to rock out w/ cli-aoke on OS X El Cap

### ISSUE THREAD

**Issue by hernamesbarbara** [jfrazelle/cliaoke#6]
I can't for the life of me get cli-aoke to work on the newest version of OS X. 

the `sing ` command always returns as follows

```
hernamesbarbara at hernamesbarbara-MBP in ~
$ cli-aoke sing Jay-Z_-_Hard_Knock_Life.mid
DJ cli-aoke on the request line.
Bringing up the track...
Fetching lyrics...
Sowwwwyyyyy
Search for Jay-Z_-_Hard_Knock_Life.mid returned zero results.
```

**Comment by jfrazelle** [comment]
noooooo this is a travesty :( i will try it out

On Thu, Nov 5, 2015 at 3:08 PM, Austin O. <notifications@github.com> wrote:

> I can't for the life of me get cli-aoke to work on the newest version of
> OS X.
>
> the sing command always returns as follows
>
> hernamesbarbara at hernamesbarbara-MBP in ~
> $ cli-aoke sing Jay-Z_-_Hard_Knock_Life.mid
> DJ cli-aoke on the request line.
> Bringing up the track...
> Fetching lyrics...
> Sowwwwyyyyy
> Search for Jay-Z_-_Hard_Knock_Life.mid returned zero results.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/cli-aoke/issues/6>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Rewrite it in go whoop
